name: Deploy Microservices


on:
  push:
    branches:
      - main



jobs:


  api-gateway:

    runs-on: ubuntu-latest

    steps:

    - name: Deploy API Gateway

      uses: appleboy/ssh-action@v1.0.3

      with:

        host: ${{ secrets.API_HOST }}

        username: ubuntu

        key: ${{ secrets.SSH_KEY }}

        script: |

          cd microservice/backend/api-gateway

          git pull

          npm install

          pm2 restart api-gateway



  order-service:


    runs-on: ubuntu-latest


    steps:


    - name: Deploy Order


      uses: appleboy/ssh-action@v1.0.3


      with:


        host: ${{ secrets.ORDER_HOST }}

        username: ubuntu

        key: ${{ secrets.SSH_KEY }}


        script: |


          cd microservice/backend/order

          git pull

          npm install

          pm2 restart order




  services:


    runs-on: ubuntu-latest


    steps:


    - name: Deploy Services


      uses: appleboy/ssh-action@v1.0.3


      with:


        host: ${{ secrets.SERVICE_HOST }}

        username: ubuntu

        key: ${{ secrets.SSH_KEY }}


        script: |


          cd microservice/backend/services

          git pull

          npm install

          pm2 restart services